version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image:  mysql:8.0.33-debian
    restart: always
    environment:
      MYSQL_DATABASE: bestwedo_zaestitches
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%' # allow remote access
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
    security_opt:
    - seccomp:unconfined

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - laravel

volumes:
  mysql_data:


networks:
  laravel:
